zeebe:
  host: 127.0.0.1:26500
  plaintext: true

ffmpeg:
  ffprobe: "ffprobe"
  ffmpeg: "ffmpeg"

video2x:
  executable: "python3.9 /home/patrick/Documents/Projects/zeebe/video2x/src/video2x.py"

rife:
  executable: "python3 /home/patrick/Documents/Projects/zeebe/arXiv2020-RIFE/inference_video.py --model /home/patrick/Documents/Projects/zeebe/arXiv2020-RIFE/train_log/"
