version: "3.5"

services:
  zeebe:
    image: camunda/zeebe:0.26.0
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  monitor:
    image: camunda/zeebe-simple-monitor:0.19.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    # volumes:
    #   - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "miniominio"
    volumes:
      - minio_data:/data
    command: server /data/minio
    networks:
      - zeebe_network

volumes:
  minio_data:

networks:
  zeebe_network:
