version: "3.5"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "miniominio"
    volumes:
      - minio-data:/data
    command: server /data/minio
    ports:
      - 9000:9000

volumes:
  minio-data:
