zeebe:
  worker:
    hazelcast:
      connection: zeebe:5701

  client:
    broker.contactPoint: zeebe:26500
    security.plaintext: true

spring:
  datasource:
    url: jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1
    user: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
